[workspace]
authors = ["Egor Masterskikh <masterskikh.egor@gmail.com>"]
channels = ["conda-forge"]
name = "montreal-forced-aligner"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
kaldi = ">=5.5.1112,<6"
librosa = ">=0.11.0,<0.12"
biopython = ">=1.85,<2"
praatio = ">=6.2.0,<7"
tqdm = ">=4.67.1,<5"
requests = ">=2.32.4,<3"
colorama = ">=0.4.6,<0.5"
pyyaml = ">=6.0.2,<7"
pynini = ">=2.1.6.post1,<3"
openfst = ">=1.8.3,<2"
baumwelch = ">=0.3.9,<0.4"
ngram = ">=1.3.16,<2"
