[workspace]
authors = ["Egor Masterskikh <masterskikh.egor@gmail.com>"]
channels = ["conda-forge"]
name = "montreal-forced-aligner"
platforms = ["win-64"]
version = "0.1.0"
preview = ["pixi-build"]

[package]

[tasks]

# minimal
[dependencies]
baumwelch = ">=0.3.9,<0.4"
ffmpeg = ">=7.1.1,<8"
hdbscan = ">=0.8.39,<0.9"
kalpy = ">=0.7.0,<0.8"
kneed = ">=0.8.5,<0.9"
ngram = ">=1.3.16,<2"
pgvector-python = ">=0.4.1,<0.5"
rich-click = ">=1.8.9,<2"
seaborn = ">=0.13.2,<0.14"
setuptools-scm = ">=8.3.1,<9"
sox = ">=14.4.2,<15"
spacy = ">=3.8.6,<4"
psycopg2 = ">=2.9.9,<3"

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.7.1, <3", index = "https://download.pytorch.org/whl/cpu" }

[pypi-dependencies]
whisperx = ">=3.4.2, <4"

[feature.dev.dependencies]
mock = ">=5.2.0,<6"
pytest = ">=8.4.1,<9"

# https://pixi.sh/latest/integration/editor/jetbrains/
[feature.pycharm-integration.dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"

[environments]
default = ["cpu"]
dev = ["dev", "pycharm-integration"]
